name: Nicolas Le Corvec
author: Nicolas Le Corvec
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-feed

url: http://nicolaslecorvec.github.io

navigation:
- root: Home
  url: /
- root: CV
  url: /cv
- root: Research
  url: /research
  first-level:
    - text: Stability of volcanic edifices
    url: /research/stability/index.html
    - text: Spatial distribution of monogenetic volcanic vents
    url: /research/spatialdistrib/index.html
    - text: Magmato-tectonic interactions
    url: /research/magmatotecto/index.html
    - text: Stability of magma reservoirs
    url: /research/stabilityreservoirs/index.html
    - text: Crustal magma reorientation
    url: /research/magmareorient/index.html
- root: Publications
  url: /publications
- root: Twitter
  url: /twitter
